version: "3"
services:

  Vue:
    image: frontend:latest
    ports: 
      - 80:80
    networks:
      - frontend
      - combine_network
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure 

  db:
    image: seniorcapstone:latest
    ports: 
      - 3306:3306
    networks:
      - backend 
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - my-datavolume:/var/lib/mysql
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: seniorcapstone

  Node:
    image: backend:latest
    ports:
      - 3000:3000
    networks:
      - backend
      - combine_network
    volumes:
      - /Users/johnminhdo/Desktop/Bird-Box/UI/backEnd:/app/
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure

  Sample:
    image: sample:latest
    ports:
      - 81:81 
    networks:
      - backend 
    volumes:
      - /Users/johnminhdo/Desktop/CSC_404/Bird-Box/Python:/app
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure


  

networks:
  frontend:
  backend:
  combine_network:

volumes: 
  my-datavolume: 
    

