version: "3"
services:

  Vue:
    image: frontend:latest
    ports: 
      - 80:80
    networks:
      - frontend
      - combine_network
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure 

  Node:
    image: backend:latest
    ports:
      - 3000:3000
    networks:
      - backend
      - combine_network
    volumes:
      - /Users/johnminhdo/Desktop/Bird-Box/UI/backEnd:/app/
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure


  

networks:
  frontend:
  backend:
  combine_network:

    

