# Description: This creates the custom image to create the containter along with setting up the applications
# along with their dependencies, libraries, packages, etc.
# This also exposed port to be accessed from the localhost 

FROM vuejs/ci:latest 

RUN mkdir -p /app

WORKDIR /app

COPY package.json /app/package.json 

RUN npm install 

COPY . /app 

ENV PORT 80

EXPOSE 80 



CMD ["npm", "run", "serve"]