FROM node:10.18.1

RUN apt-get update && apt-get install -y ffmpeg

RUN npm install -g nodemon

RUN npm config set registry https://registry.npmjs.org

RUN mkdir -p /app

WORKDIR /app

COPY package.json /app/package.json

RUN npm install 

COPY . /app

EXPOSE 3000

CMD ["nodemon"]