version: "3"
services:

  Vue:
    image: frontend:latest
    ports: 
      - 80:80
    networks:
      - frontend 
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure 

  db:
    image: seniorcapstone:latest
    ports: 
      - 3306:3306
    networks:
      - backend 
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - my-datavolume:/var/lib/mysql
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: seniorcapstone

  Node:
    image: backend:latest
    networks:
      - backend 
    volumes:
      - /Users/johnminhdo/Desktop/CSC_404/Bird-Box/UI/backEnd:/app
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure

  

networks:
  frontend:
  backend:

volumes: 
  my-datavolume: 
    

